### PR TITLE
Update login & home page

### PR DESCRIPTION
**Pull request by majicmaj**
image
image

### CODE REVIEW

**Review by cmkrist — APPROVED** [review]
Looks good

**Comment by hex2f** [comment]
Contrast is quite weak on the sign-in page, other than that lgtm!

**Comment by majicmaj** [comment]
Addressed contrast concerns by increasing contrast and adding border
Also changed color from stone to zinc (a bit colder of a gray) for aesthetic improvements.

**Review by hex2f — COMMENTED** [review]
lgtm!

**Pull request merged**
